name: Run Zap Full Scan on Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  issues: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-zap-full:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: ZAP Full
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: ${{ vars.TEST_SITE_URL }}
